"""
Project setup & scaffolding  - main.py
Generated by GitStreak AI
Stack: python-fastapi
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import uvicorn

app = FastAPI(
    title="Project setup & scaffolding ",
    description="Auto-generated by GitStreak AI",
    version="0.1.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    id: Optional[int] = None
    name: str
    description: Optional[str] = ""
    completed: bool = False

items_db: List[Item] = []
_next_id = 1

@app.get("/", tags=["root"])
async def root():
    return {"message": "Welcome to Project setup & scaffolding ", "status": "running"}

@app.get("/items", response_model=List[Item], tags=["items"])
async def list_items():
    return items_db

@app.post("/items", response_model=Item, status_code=201, tags=["items"])
async def create_item(item: Item):
    global _next_id
    item.id = _next_id
    _next_id += 1
    items_db.append(item)
    return item

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
